
combine_control_expr = false
format_code_in_doc_comments = true
format_generated_files = false
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
edition = "2021"
